#!/usr/bin/env python

import json
from httplib import HTTPConnection
from subprocess import PIPE, Popen
from time import time
from urlparse import urlparse


AUTH_HOSTPORT = 'auth1.stg:80'
AUTH_PATH = '/auth/v1.0'
AUTH_USER = 'act:usr'
AUTH_KEY = 'pwd'
STOR_HOSTPORT = 'proxy1-z1.stg:80'
CONT_NAME = 'walt'

conn = HTTPConnection(AUTH_HOSTPORT)
conn.request('GET', AUTH_PATH,
             headers={'x-auth-user': AUTH_USER, 'x-auth-key': AUTH_KEY})
resp = conn.getresponse()
auth_token = resp.getheader('x-auth-token')
data = json.loads(resp.read())
stor_path = urlparse(data['storage'][data['storage']['default']]).path
acct_name = stor_path.split('/')[-1]
cont_path = stor_path + '/' + CONT_NAME

conn = HTTPConnection(STOR_HOSTPORT)
conn.request('PUT', cont_path, headers={'x-auth-token': auth_token})
conn.getresponse().read()

pope = Popen(['swift-get-nodes', '/etc/swift/container.ring.gz', acct_name, CONT_NAME], stdout=PIPE)
cont_durl = None
for line in pope.communicate()[0].split('\n'):
    if line.startswith('curl'):
    cont_durl = line.split('"')[1]
        break

print cont_durl

begin = time()
tests = '2x100000c5'
pope = Popen(['dsh', '-Mcg', 'proxy-all', './walt -D %s %s' % (cont_durl, tests)])
pope.communicate()
print '%.05fs %s' % (time() - begin, tests)
