#!/usr/bin/env python

from sys import stdin


disks = {}
percents = {}

for line in stdin:
    data = line.strip().split()
    disk = data[0] + data[-1]
    percent = int(data[-2][:-1])
    disks[disk] = percent
    percents[percent] = percents.get(percent, 0) + 1

mul = 69.0 / max(percents.values())
for percent in sorted(percents):
    print '% 3d%% % 4d %s' % (percent, percents[percent], '*' * int(percents[percent] * mul))
