#!/usr/bin/env python

import sys

from swift.common import db


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit('Syntax: %s <account> <container_db_file>' % sys.argv[0])
    cb = db.ContainerBroker(sys.argv[2])
    info = cb.get_info()
    if info['account'] == sys.argv[1]:
        print sys.argv[2]
        cb.reported('0', '0', 0, 0)
