#!/usr/bin/env python

import sys
from swift.common.ring import Ring

ringfile = sys.argv[1]

ring = Ring(ringfile)

devs = []
for ipdevice in sys.argv[2:]:
    if not [d for d in ring.devs if '%s/%s' % (d['ip'], d['device']) == ipdevice]:
        raise Exception('could not resolve ' + ipdevice)

lost = []
for part in xrange(ring.partition_count):
    if not [d for d in ring.get_part_nodes(part) if '%s/%s' % (d['ip'], d['device']) not in sys.argv[2:]]:
        lost.append(part)

print len(lost)
if len(lost) < 1000:
    print lost
